### ISSUE TITLE
Missing archive and signature for release 1.2

### ISSUE THREAD

**Issue by freswa** [fwupd/fwupd-efi#20]
At https://people.freedesktop.org/~hughsient/releases/ there is the checksum for release 1.2, but the tarball and the signature is missing. Is this intentional?

**Comment by hughsie** [comment]
Ahh, I uploaded them to the github release, but must have forgotten the scp step. Thanks for the reminder.

**Comment by freswa** [comment]
@hughsie Thanks :+1:  May I ask for a upload of the signature (.asc) too? :)

**Comment by hughsie** [comment]
Done.
