### ISSUE TITLE
Missing fwupdx64.efi.signed

### ISSUE THREAD

**Issue by FFY00** [fwupd/fwupd-efi#5]
I split the arch package to fwupd and fwupd-efi and someone just noticed right now that `fwupdx64.efi.signed` is missing.

Here are the build instructions: https://github.com/archlinux/svntogit-community/blob/packages/fwupd-efi/trunk/PKGBUILD

What should be causing this issue?

**Comment by superm1** [comment]
In the past how was signing handled in arch? Is there a private key on any infrastructure that signs efi binaries?

**Comment by FFY00** [comment]
No. I think I just misunderstood the issue. Looks like we didn't ship that, but fwupd is looking for it, apparently because of the regression fixed here https://github.com/fwupd/fwupd/commit/197d3dc3b9acb93be30c4a7f49e8c0ad3f554818.

**Comment by FFY00** [comment]
I backported that fix and everything is reportedly working now. Sorry for the noise!
