### ISSUE TITLE
fwupd-efi-1.0: PermissionError: [Errno 13] Permission denied: 'genpeimg' (build fails)

### ISSUE THREAD

**Issue by m1027** [fwupd/fwupd-efi#9]
Could someone please have a look on this:

I fail to build fwupd-efi-1.0 on Gentoo due to
```
PermissionError: [Errno 13] Permission denied: 'genpeimg'
```

With the help from the Gentoo people (https://bugs.gentoo.org/796569#c2) we
can say that there isn't (and shouldn't be) any genpeimg on my OS at all. But
somehow the code execution behaves as if it was present. So, in may case the
code execution should return early here

https://github.com/fwupd/fwupd-efi/blob/d74ab0fe15bc15999c81469537763cc1293bb86c/efi/generate_binary.py#L57

but in fact it continues, and later fails with the above error.

FYI: During the build, even meson confirms that genpeimg is *not* present on
my system:

```
Program genpeimg found: NO
```

IMHO I had that issue in fwupd-1.5.9 (when it was bundled with fwupd-efi),
then being fixed in fwupd-1.6.0 and 1.6.1, and finally returned in
Gentoo-1.6.1-r1, with fwupd-efi-1.0 being separated.

Any ideas? I believe this could well be something trivial...

**Comment by superm1** [comment]
I think it's fixed by https://github.com/fwupd/fwupd-efi/commit/321f0750ee69cc62ab609f760769d880676f712b

**Comment by m1027** [comment]
Thanks a lot, issue solved by applying the most recent commits.

**Comment by Whissi** [comment]
But the patch will break building for me:

```
[7/7] /var/tmp/portage/sys-apps/fwupd-efi-1.0/work/fwupd-efi-1.0/efi/generate_binary.py efi/fwup.so efi/fwupdx64.efi --arch x86_64 --objcopy x86_64-pc-linux-gnu-objcopy --genpeimg ''
FAILED: efi/fwupdx64.efi
/var/tmp/portage/sys-apps/fwupd-efi-1.0/work/fwupd-efi-1.0/efi/generate_binary.py efi/fwup.so efi/fwupdx64.efi --arch x86_64 --objcopy x86_64-pc-linux-gnu-objcopy --genpeimg ''
usage: generate_binary.py [-h] [--objcopy OBJCOPY] [--arch ARCH] infile outfile
generate_binary.py: error: unrecognized arguments: --genpeimg
ninja: build stopped: subcommand failed.
```

**Comment by m1027** [comment]
Yeah, see my post in bugs.gentoo.org. 

(Try all recent patches simply by using version 9999.)

**Comment by Whissi** [comment]
Yeah, found the two patches, thank you! Fixed package is now available in Gentoo.

**Comment by superm1** [comment]
This thread makes it apparent we should tag a new release. @hughsie can you do that next week?

**Comment by hughsie** [comment]
> can you do that next week

Done!

**Comment by superm1** [comment]
Did you forget to push tag?

**Comment by hughsie** [comment]
I don't _think_ so... https://github.com/fwupd/fwupd-efi/releases/tag/1.1

**Comment by superm1** [comment]
Yeah it's tagged, but it's not getting marked as latest release.  See https://github.com/fwupd/fwupd-efi/releases.  I think we have something extra missing in CI that we do in fwupd that makes that magic happen.
